-- ============================================================================
-- ANTI-ABUSE-v2.8.1 — force public writes through the Turnstile gateway
--
-- Revokes EXECUTE from the implicit PUBLIC role as well as anon/authenticated.
-- This matters: PostgreSQL grants EXECUTE to PUBLIC by default when a function is
-- created, and anon/authenticated inherit PUBLIC's privileges — so revoking only
-- from anon/authenticated would leave the direct-RPC bypass open via PUBLIC.
-- Only service_role (used by the submit-budget / submit-event-response Edge
-- Functions, which first verify a Cloudflare Turnstile token) may execute these.
-- Public READS and local allocation are unaffected.
--
-- DO NOT APPLY until:
-- 1. both Edge Functions are deployed,
-- 2. server secrets are configured,
-- 3. both gateway write flows are verified in production,
-- 4. the frontend is live and routing writes through the gateway.
--
-- Rollback (see docs/anti-abuse-gateway-runbook.md): re-grant EXECUTE to
-- anon, authenticated (and, if needed, PUBLIC) via a compensating forward
-- migration — do not edit this file after it is applied.
-- ============================================================================

revoke execute on function public.submit_vote(
  uuid,
  text,
  smallint,
  text,
  jsonb
) from public, anon, authenticated;

revoke execute on function public.record_event_response(
  text,
  uuid,
  text
) from public, anon, authenticated;

grant execute on function public.submit_vote(
  uuid,
  text,
  smallint,
  text,
  jsonb
) to service_role;

grant execute on function public.record_event_response(
  text,
  uuid,
  text
) to service_role;
